name: VHub Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run VHub Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./VHub.Media/VHub.Media.sln

      - name: Build
        run: dotnet build ./VHub.Media/VHub.Media.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./VHub.Media/VHub.Media.sln --no-build --verbosity normal --configuration Release